### ISSUE TITLE
a2sketch text rendering re-fixed?

### ISSUE THREAD

**Issue by arnehilmann** [gerald1248/kubernetes-open-source-slides#3]
Does the lines
https://github.com/gerald1248/kubernetes-open-source-slides/blob/c5c761b01344335333c2bd4110b3fca4c429411e/assets/css/slides.scss#L192

fix this issue here?
https://github.com/arnehilmann/a2sketch/issues/3

**Comment by gerald1248** [comment]
Thanks Arne! Just spotted this, apologies!
